# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

calculate_impact_task:
  description: >
    Using the provided asteroid parameters (size: {size}, speed: {speed}, impact angle: {angle}, and composition: {composition}),
    calculate the estimated impact energy, crater size, and potential effects on Earth.
    Use scientific formulas and, if needed, external libraries or APIs.
  expected_output: >
    A summary of the calculations, including:
    - Impact energy (in megatons of TNT)
    - Estimated crater diameter (in km)
    - Potential local and global effects
    - Any interesting scientific facts about the impact
  agent: asteroid_data_scientist

write_impact_report_task:
  description: >
    Take the calculated impact summary and write a concise, dramatic, engaging, and informative 
    report for a general audience. Use analogies and comparisons to help readers 
    understand the scale of the event. Keep the report brief and to the point.
  expected_output: >
    A markdown-formatted report with:
    - A catchy title
    - A short introduction
    - A concise description of the impact and its effects
    - 1-2 fun facts or historical comparisons
  agent: impact_reporter
